version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URI: mongodb://mongo:27017/task3
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
