version: '3.8'

services:
  todo:
    image: diamol/ch06-todo-list
    container_name: todo-container
    restart: unless-stopped  
    ports:
      - "80:80"  
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - todo-db:/var/lib/postgresql/data  
volumes:
  todo-db:
