version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend-container
    networks:
      - frontend_network
    ports:
      - "80:80"

  backend:
    build: ./backend
    container_name: backend-container
    networks:
      - frontend_network
      - backend_network
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: task6

  postgres:
    image: postgres:11.5-alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./db/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task6
      DB_HOST: postgres
      DB_PORT: 5432
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  postgres-volume:
